import type { Metadata } from "next";
import { TranscriptTool } from "@/components/tools/TranscriptTool";
import { Breadcrumbs, OtherTools, ToolSchema } from "@/components/tools/ToolSchema";

// Title targets the two highest-volume terms from the competitor gap analysis:
// "youtube transcript" (~182K) + "youtube to transcript" (~94K). The root layout
// appends " | Clips" via its title template, so we don't repeat the brand here.
const TITLE = "YouTube to Transcript - Free, No Sign-Up";
const DESCRIPTION =
  "Free YouTube transcript generator. Paste any YouTube link to get the full transcript in seconds - copy it or download as TXT or SRT with timestamps. No sign-up, no API key.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  keywords: [
    "youtube transcript",
    "youtube to transcript",
    "get youtube transcript",
    "youtube transcript generator",
    "youtube video to text",
    "download youtube transcript",
    "youtube captions to text",
    "transcribe youtube video",
    "free transcript generator",
  ],
  alternates: { canonical: "/tools/youtube-to-transcript" },
  openGraph: {
    title: `${TITLE} | Clips`,
    description: DESCRIPTION,
    type: "website",
    url: "/tools/youtube-to-transcript",
    images: ["/og/youtube-to-transcript.png"],
  },
  twitter: {
    card: "summary_large_image",
    title: `${TITLE} | Clips`,
    description: DESCRIPTION,
    images: ["/og/youtube-to-transcript.png"],
  },
};

const STEPS = [
  {
    n: "1",
    title: "Paste a YouTube link",
    body: "Copy the URL of any public YouTube video and paste it into the box above.",
  },
  {
    n: "2",
    title: "We pull the captions",
    body: "We fetch the video's caption track instantly - manual subtitles when available, otherwise YouTube's auto-generated captions.",
  },
  {
    n: "3",
    title: "Copy or download",
    body: "Read it on screen, toggle timestamps, then copy the text or download it as a .txt or .srt file.",
  },
];

const FEATURES = [
  ["100% free", "No sign-up, no credit card, no watermark. Use it as often as you like."],
  ["Timestamps + plain text", "Switch between a clean paragraph view and a timestamped view in one click."],
  ["TXT & SRT export", "Download as plain text for notes, or as an .srt subtitle file for editors."],
  ["Any language", "Works with every caption language a video offers, including auto-translated tracks."],
];

const FAQS: { q: string; a: string }[] = [
  {
    q: "Is this YouTube transcript tool really free?",
    a: "Yes. It's completely free with no sign-up and no limits - paste a link and get the transcript. It's a free tool from Clips, our AI that turns long videos into short clips.",
  },
  {
    q: "How do I get the transcript of a YouTube video?",
    a: "Copy the video's URL, paste it into the box above, and click Get transcript. Within seconds you'll see the full transcript, which you can copy or download as a TXT or SRT file.",
  },
  {
    q: "Does the video need captions?",
    a: "Yes - the tool reads the video's caption track. Most YouTube videos have captions, either uploaded by the creator or auto-generated by YouTube. If a video has captions turned off entirely, there's no transcript to fetch.",
  },
  {
    q: "Can I download the transcript with timestamps?",
    a: "Yes. Toggle the Timestamps view to see each line with its time, and use the .srt download to get a subtitle file with precise start/end times for use in a video editor.",
  },
  {
    q: "Can I turn the video into short clips too?",
    a: "Yes - that's what Clips does. After you get a transcript, hit 'Make clips - free' to turn the same video into ranked, captioned, vertical shorts automatically.",
  },
];

export default function YoutubeToTranscriptPage() {
  return (
    <div>
      <ToolSchema
        slug="youtube-to-transcript"
        name="YouTube to Transcript"
        description={DESCRIPTION}
        faqs={FAQS}
      />
      <Breadcrumbs name="YouTube to Transcript" />

      {/* ── Hero ─────────────────────────────────────────────────────────── */}
      <section className="text-center">
        <p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand-300">
          Free tool
        </p>
        <h1 className="mx-auto mt-4 max-w-3xl text-balance text-4xl font-semibold leading-[1.08] tracking-tight sm:text-5xl">
          YouTube to Transcript
        </h1>
        <p className="mx-auto mt-4 max-w-2xl text-base text-ink-300 sm:text-lg">
          Paste any YouTube link and get the full transcript in seconds - copy it or
          download it as TXT or SRT. Free, no sign-up, no API key.
        </p>
      </section>

      {/* ── The tool ─────────────────────────────────────────────────────── */}
      <section className="mx-auto mt-8 max-w-3xl">
        <TranscriptTool />
      </section>

      {/* ── SEO intro copy (keyword-rich, real value) ────────────────────── */}
      <section className="mx-auto mt-14 max-w-2xl text-ink-300">
        <p className="text-base leading-7">
          This free <strong className="text-white">YouTube transcript generator</strong> pulls
          the full text of any public YouTube video in seconds - no sign-up, no
          software, no API key. Whether you want to read a video instead of
          watching it, repurpose a podcast into a blog post, study a lecture, or
          grab quotes for social posts, you can{" "}
          <strong className="text-white">convert a YouTube video to text</strong> and copy or
          download it instantly.
        </p>
        <p className="mt-4 text-base leading-7">
          It works with both creator-uploaded subtitles and YouTube&apos;s
          auto-generated captions, in any available language. Export the
          transcript as a plain <strong className="text-white">.txt</strong> file for notes and
          articles, or as a timestamped <strong className="text-white">.srt</strong> subtitle file
          for video editors.
        </p>
      </section>

      {/* ── How it works ─────────────────────────────────────────────────── */}
      <section className="mt-16">
        <h2 className="text-center text-2xl font-semibold tracking-tight">
          How to get a YouTube transcript
        </h2>
        <div className="mt-8 grid gap-4 sm:grid-cols-3">
          {STEPS.map((s) => (
            <div
              key={s.n}
              className="rounded-2xl border border-white/10 bg-ink-850 p-5 shadow-rim"
            >
              <span className="grid h-9 w-9 place-items-center rounded-full bg-brand/15 text-sm font-bold text-brand-300">
                {s.n}
              </span>
              <h3 className="mt-3 text-sm font-semibold text-white">{s.title}</h3>
              <p className="mt-1.5 text-sm text-ink-300">{s.body}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── Features ─────────────────────────────────────────────────────── */}
      <section className="mt-16">
        <h2 className="text-center text-2xl font-semibold tracking-tight">
          Why use our free transcript tool
        </h2>
        <div className="mt-8 grid gap-4 sm:grid-cols-2">
          {FEATURES.map(([title, body]) => (
            <div
              key={title}
              className="rounded-2xl border border-white/10 bg-ink-900/45 p-5 shadow-rim"
            >
              <h3 className="text-sm font-semibold text-white">{title}</h3>
              <p className="mt-1.5 text-sm text-ink-300">{body}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── FAQ ──────────────────────────────────────────────────────────── */}
      <section className="mx-auto mt-16 max-w-3xl">
        <h2 className="text-center text-2xl font-semibold tracking-tight">
          Frequently asked questions
        </h2>
        <div className="mt-8 space-y-3">
          {FAQS.map((f) => (
            <details
              key={f.q}
              className="group rounded-2xl border border-white/10 bg-ink-850 p-5 shadow-rim"
            >
              <summary className="flex cursor-pointer list-none items-center justify-between text-sm font-semibold text-white">
                {f.q}
                <span className="ml-4 shrink-0 text-ink-400 transition group-open:rotate-45">+</span>
              </summary>
              <p className="mt-3 text-sm leading-6 text-ink-300">{f.a}</p>
            </details>
          ))}
        </div>
      </section>

      {/* ── Cross-link to the other free tools (internal SEO) ────────────── */}
      <OtherTools currentSlug="youtube-to-transcript" />

      {/* ── Closing CTA ──────────────────────────────────────────────────── */}
      <section className="mt-16 rounded-3xl border border-white/10 bg-gradient-to-b from-brand/[0.10] to-transparent p-8 text-center sm:p-12">
        <h2 className="text-2xl font-semibold tracking-tight sm:text-3xl">
          Turn that video into viral clips
        </h2>
        <p className="mx-auto mt-3 max-w-xl text-ink-300">
          Clips reads the whole video and emails you the 10 best moments as ranked,
          captioned, vertical shorts - in about 30 minutes.
        </p>
        <a
          href="/new"
          className="mt-6 inline-flex items-center gap-2 rounded-full bg-gradient-to-b from-brand-400 to-brand px-6 py-3 text-sm font-semibold text-white shadow-glow transition duration-200 ease-premium hover:from-brand hover:to-brand-600 active:scale-95"
        >
          Make clips - free
        </a>
      </section>
    </div>
  );
}
