import { Body, Controller, HttpCode, Logger, Post, UseGuards } from '@nestjs/common';
import { spawn } from 'node:child_process';
import * as path from 'node:path';
import { TranscriptDto } from './dto/transcript.dto';
import { TranscriptRateLimitGuard } from './rate-limit.guard';

// Repo root: pipeline/transcript.py resolves relative to here.
// This file is app/api/src/transcript/transcript.controller.ts → up 4 to root.
const REPO_ROOT =
  process.env.PIPELINE_REPO_ROOT || path.resolve(__dirname, '..', '..', '..', '..');
const PYTHON_BIN = process.env.PYTHON_BIN || 'python';

/** One caption event from pipeline/transcript.py. */
interface TranscriptSegment {
  start: number;
  dur: number;
  text: string;
}

/** Raw JSON line printed by pipeline/transcript.py (success or {error,code}). */
interface TranscriptPy {
  title?: string;
  channel?: string;
  duration?: number;
  video_id?: string;
  thumbnail?: string;
  language?: string;
  auto_generated?: boolean;
  available_languages?: string[];
  segments?: TranscriptSegment[];
  text?: string;
  error?: string;
  code?: string;
}

/** camelCase view returned to the web client. */
interface TranscriptView {
  ok: boolean;
  title: string;
  channel: string;
  durationSec: number;
  videoId: string;
  thumbnailUrl: string;
  language: string;
  autoGenerated: boolean;
  availableLanguages: string[];
  segments: TranscriptSegment[];
  text: string;
  /** Present only when ok=false: a friendly message + a stable machine code. */
  error?: string;
  errorCode?: string;
}

const EMPTY: Omit<TranscriptView, 'ok' | 'error' | 'errorCode'> = {
  title: '',
  channel: '',
  durationSec: 0,
  videoId: '',
  thumbnailUrl: '',
  language: '',
  autoGenerated: false,
  availableLanguages: [],
  segments: [],
  text: '',
};

/**
 * FREE "YouTube to Transcript" tool (public, no auth, NO API keys). Spawns
 * pipeline/transcript.py which pulls a video's caption track via yt-dlp WITHOUT
 * downloading the video and WITHOUT touching any paid API (Groq/Gemini). This is
 * a deliberate organic-SEO surface, separate from the paid clip pipeline.
 *
 * Always returns 200 with { ok }, never a 500 - a bad/keyless/caption-less video
 * yields ok:false + a friendly message the UI renders inline.
 */
@Controller('transcript')
export class TranscriptController {
  private readonly logger = new Logger(TranscriptController.name);

  @Post()
  @HttpCode(200)
  @UseGuards(TranscriptRateLimitGuard)
  async fetch(@Body() dto: TranscriptDto): Promise<TranscriptView> {
    let py: TranscriptPy;
    try {
      py = await this.runTranscriptPy(dto.url, dto.lang);
    } catch (e) {
      this.logger.warn(`transcript.py unavailable for ${dto.url}: ${(e as Error).message}`);
      return {
        ok: false,
        ...EMPTY,
        error: 'The transcript service is temporarily unavailable. Please try again.',
        errorCode: 'unavailable',
      };
    }

    if (py.error || !py.segments || py.segments.length === 0) {
      return {
        ok: false,
        ...EMPTY,
        availableLanguages: py.available_languages ?? [],
        error: py.error ?? 'No transcript could be produced for this video.',
        errorCode: py.code ?? 'no_transcript',
      };
    }

    return {
      ok: true,
      title: py.title ?? '',
      channel: py.channel ?? '',
      durationSec: Number(py.duration) || 0,
      videoId: py.video_id ?? '',
      thumbnailUrl: py.thumbnail ?? '',
      language: py.language ?? '',
      autoGenerated: !!py.auto_generated,
      availableLanguages: py.available_languages ?? [],
      segments: py.segments,
      text: py.text ?? '',
    };
  }

  private runTranscriptPy(url: string, lang?: string): Promise<TranscriptPy> {
    const args = ['--url', url];
    if (lang) args.push('--lang', lang);
    return this.runPy<TranscriptPy>('pipeline/transcript.py', args);
  }

  /**
   * Spawn a pipeline python helper that prints exactly one JSON line and exits 0
   * even on error (transcript.py / yt_tags.py both follow this contract), and
   * parse that line. Only rejects on a real spawn failure, timeout, or bad JSON.
   */
  private runPy<T>(script: string, scriptArgs: string[]): Promise<T> {
    const args = [script, ...scriptArgs];
    return new Promise((resolve, reject) => {
      const child = spawn(PYTHON_BIN, args, { cwd: REPO_ROOT });
      let stdout = '';
      let stderrTail = '';
      let settled = false;

      // Bound the wait so a hung yt-dlp extract can't pin a request open. A
      // metadata/caption extract is a couple of network round-trips; 40s is generous.
      const timer = setTimeout(() => {
        if (settled) return;
        settled = true;
        child.kill();
        reject(new Error(`${script} timed out`));
      }, 40_000);

      child.stdout.setEncoding('utf-8');
      child.stdout.on('data', (c: string) => (stdout += c));
      child.stderr.setEncoding('utf-8');
      child.stderr.on('data', (c: string) => (stderrTail = (stderrTail + c).slice(-2000)));

      child.on('error', (e) => {
        if (settled) return;
        settled = true;
        clearTimeout(timer);
        reject(new Error(`Failed to spawn ${script}: ${e.message}`));
      });

      child.on('close', () => {
        if (settled) return;
        settled = true;
        clearTimeout(timer);
        // Take the last non-empty line so yt-dlp warnings before the JSON are ignored.
        const line = stdout
          .split('\n')
          .map((l) => l.trim())
          .filter(Boolean)
          .pop();
        if (!line) {
          if (stderrTail.trim()) this.logger.warn(`${script} stderr: ${stderrTail.trim()}`);
          return reject(new Error(`${script} produced no output`));
        }
        try {
          resolve(JSON.parse(line) as T);
        } catch (e) {
          reject(new Error(`${script} bad JSON: ${(e as Error).message}`));
        }
      });
    });
  }

  // ── Tags extractor ──────────────────────────────────────────────────────
  @Post('tags')
  @HttpCode(200)
  @UseGuards(TranscriptRateLimitGuard)
  async tags(@Body() dto: TranscriptDto): Promise<TagsView> {
    let py: TagsPy;
    try {
      py = await this.runPy<TagsPy>('pipeline/yt_tags.py', ['--url', dto.url]);
    } catch (e) {
      this.logger.warn(`yt_tags.py unavailable for ${dto.url}: ${(e as Error).message}`);
      return { ...EMPTY_TAGS, ok: false, error: 'The tags service is temporarily unavailable. Please try again.', errorCode: 'unavailable' };
    }
    if (py.error && py.code !== 'no_tags') {
      return { ...EMPTY_TAGS, ok: false, error: py.error, errorCode: py.code ?? 'extract_failed' };
    }
    const tags = py.tags ?? [];
    return {
      ok: true,
      title: py.title ?? '',
      channel: py.channel ?? '',
      videoId: py.video_id ?? '',
      thumbnailUrl: py.thumbnail ?? '',
      tags,
      categories: py.categories ?? [],
      viewCount: Number(py.view_count) || 0,
      // A video with zero public tags is a valid (empty) result, not an error.
      ...(tags.length === 0 ? { error: 'This video has no public tags.', errorCode: 'no_tags' } : {}),
    };
  }
}

/** Raw JSON from pipeline/yt_tags.py. */
interface TagsPy {
  title?: string;
  channel?: string;
  video_id?: string;
  thumbnail?: string;
  tags?: string[];
  categories?: string[];
  view_count?: number;
  error?: string;
  code?: string;
}

/** camelCase view returned to the web client for the tags extractor. */
interface TagsView {
  ok: boolean;
  title: string;
  channel: string;
  videoId: string;
  thumbnailUrl: string;
  tags: string[];
  categories: string[];
  viewCount: number;
  error?: string;
  errorCode?: string;
}

const EMPTY_TAGS: Omit<TagsView, 'ok' | 'error' | 'errorCode'> = {
  title: '',
  channel: '',
  videoId: '',
  thumbnailUrl: '',
  tags: [],
  categories: [],
  viewCount: 0,
};
